### ISSUE TITLE
run_of_tests.py => subprocess.py: OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Wasdns** [p4lang/switch#90]
Hi all,

After long start(in other words, configure the bmv2, p4ofagent and oftest), I configured the switch with `--with-of --with-bmv2` then make it successfully. Then I tried to run openflow tests for it, but it showed the exception as I execute the command `./run_of_tests.py --oft-path /home/wasdns/oftest` in root status:

```
Traceback (most recent call last):
  File "./run_of_tests.py", line 43, in <module>
    child = Popen([oft_path] + new_args)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

I tried to add authority to it but it did not work. I have googled for it but no correct answer with my situation. 

Thank you very much if response!

**Comment by omeshF** [comment]
I have encountered the same problem. Have you @Wasdns found an answer? Can you share please?

**Comment by Wasdns** [comment]
@omeshF Unfortunately, I didn't resolve this problem. Sorry about that.
