### ISSUE TITLE
switch.L2VxlanLearnBasicTest Failed

### ISSUE THREAD

**Issue by technobilly** [p4lang/switch#94]
sudo ./bmv2/run_bm.sh
sudo ./bmv2/run_drivers.sh
sudo ./bmv2/run_tests.sh --test-dir tests/ptf-tests/api-tests

All tests PASS except one:

switch.L2VxlanLearnBasicTest ... 
L2 Vxlan Basic Mode Learn Test
Sending packet from Access port1 to Vxlan port2 and native port 3   - Learn mac on port1
Sending packet from Vxlan port2 to Access port1 and native port 3   - Learn mac on vxlan tunnel port2
FAIL

======================================================================
FAIL: switch.L2VxlanLearnBasicTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/ptf-tests/api-tests/switch.py", line 6930, in runTest
    verify_packets(self, pkt2, [swports[1], swports[3]])
  File "/usr/local/lib/python2.7/dist-packages/ptf-0.9-py2.7.egg/ptf/testutils.py", line 2279, in verify_packets
    verify_packet(test, pkt, (device, port))
  File "/usr/local/lib/python2.7/dist-packages/ptf-0.9-py2.7.egg/ptf/testutils.py", line 2226, in verify_packet
    % (device, port, result.format()))
AssertionError: Expected packet was not received on device 0, port 3.
========== EXPECTED ==========
dst        : DestMACField         = '00:11:11:11:11:11' (None)
src        : SourceMACField       = '00:22:22:22:22:22' (None)
type       : XShortEnumField      = 2048            (0)
--
version    : BitField             = 4               (4)
ihl        : BitField             = None            (None)
tos        : XByteField           = 0               (0)
len        : ShortField           = None            (None)
id         : ShortField           = 108             (1)
flags      : FlagsField           = 0               (0)
frag       : BitField             = 0               (0)
ttl        : ByteField            = 64              (64)
proto      : ByteEnumField        = 6               (0)
chksum     : XShortField          = None            (None)
src        : Emph                 = '192.168.0.1'   (None)
dst        : Emph                 = '10.10.10.1'    ('127.0.0.1')
options    : PacketListField      = []              ([])
--
sport      : ShortEnumField       = 1234            (20)
dport      : ShortEnumField       = 80              (80)
seq        : IntField             = 0               (0)
ack        : IntField             = 0               (0)
dataofs    : BitField             = None            (None)
reserved   : BitField             = 0               (0)
flags      : FlagsField           = 2               (2)
window     : ShortField           = 8192            (8192)
chksum     : XShortField          = None            (None)
urgptr     : ShortField           = 0               (0)
options    : TCPOptionsField      = {}              ({})
--
load       : StrField             = '\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-' ('')
--
0000   00 11 11 11 11 11 00 22  22 22 22 22 08 00 45 00   ......."""""..E.
0010   00 56 00 6C 00 00 40 06  A5 82 C0 A8 00 01 0A 0A   .V.l..@.........
0020   0A 01 04 D2 00 50 00 00  00 00 00 00 00 00 50 02   .....P........P.
0030   20 00 B9 CB 00 00 00 01  02 03 04 05 06 07 08 09    ...............
0040   0A 0B 0C 0D 0E 0F 10 11  12 13 14 15 16 17 18 19   ................
0050   1A 1B 1C 1D 1E 1F 20 21  22 23 24 25 26 27 28 29   ...... !"#$%&'()
0060   2A 2B 2C 2D                                        *+,-
========== RECEIVED ==========
0 total packets.
==============================

----------------------------------------------------------------------
Ran 1 test in 2.440s

FAILED (failures=1)

Regards,
Chris Sommers

**Comment by rajeevpanj** [comment]
Hi Chris,

Did you find any solution? My tests are also failing due to same reason.

Regards,
Rajeev

**Comment by chrispsommers** [comment]
Hi Rajeev,
No, I don't specifically recall this being resolved but it was a long time ago and I have not revisited it. I've moved  on to using commercial implementations.  Sorry I could not help. - Chris

**Comment by antoninbas** [comment]
This repo is not actively maintained any more AFAIK, but if you do get the tests to work, feel free to submit a patch.
